name: test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - name: Test eslint-formatter-rdjson
        run: ./eslint-formatter-rdjson/test.sh
